### ISSUE TITLE
您好， 您的数据集链接（第三个链接）没办法打开

### ISSUE THREAD

**Issue by XINGYONGZHEN** [XiangGao1102/CTSS#1]
您好， 您的数据集链接（第三个链接）没办法打开

**Comment by XiangGao1102** [comment]
您好，再看看能打开吗

**Comment by XINGYONGZHEN** [comment]
非常感谢，已经能打开了。🙌



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月23日(星期二) 凌晨1:31
收件人: "XiangGao1102/Learning-to-Incorporate-Texture-Saliency-Adaptive-Attention-to-Image-Cartoonization";
抄送: "Author";
主题: Re: [XiangGao1102/Learning-to-Incorporate-Texture-Saliency-Adaptive-Attention-to-Image-Cartoonization] 您好， 您的数据集链接（第三个链接）没办法打开 (Issue #1)





 
Closed #1 as completed.
 
&mdash;

**Comment by XiangGao1102** [comment]
好的，谢谢您的反馈



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月23日 10:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [XiangGao1102/Learning-to-Incorporate-Texture-Saliency-Adaptive-Attention-to-Image-Cartoonization] 您好， 您的数据集链接（第三个链接）没办法打开 (Issue #1) |

非常感谢，已经能打开了。🙌



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;;
发送时间: 2023年5月23日(星期二) 凌晨1:31
收件人: "XiangGao1102/Learning-to-Incorporate-Texture-Saliency-Adaptive-Attention-to-Image-Cartoonization";
抄送: "Author";
主题: Re: [XiangGao1102/Learning-to-Incorporate-Texture-Saliency-Adaptive-Attention-to-Image-Cartoonization] 您好， 您的数据集链接（第三个链接）没办法打开 (Issue #1)






Closed #1 as completed.

&mdash;
